//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mentor
    {
        public int MentorID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string CurrentJobTitle { get; set; }
        public string Organization { get; set; }
        public byte[] ProfileImage { get; set; }
        public Nullable<int> GraduationYear { get; set; }
        public string GraduationSemester { get; set; }
        public string GitHubLink { get; set; }
        public string LinkedInLink { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
